##################### Linting #############################

##################### Metrics #############################

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  CountKeywordArgs: false

##################### Performance #############################

Performance/FlatMap:
  EnabledForFlattenWithoutParams: false

Performance/RedundantBlockCall:
  Enabled: false

##################### Rails ##################################

Rails/SafeNavigation:
  ConvertTry: true

Rails/SaveBang:
  Enabled: true

##################### Security ##################################

##################### Style #################################

Style/AutoResourceCleanup:
  Enabled: true

Style/Encoding:
  Enabled: true
  EnforcedStyle: never

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

##################### Bundler #################################
Bundler/OrderedGems:
  Enabled: false
