language: ruby

rvm:
  - ruby-head
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 2.0.0-p648

sudo: false

before_install:
  - 'gem install bundler --no-document'
script:
  - 'bundle exec rspec'
after_success:
  - 'bundle exec codeclimate-test-reporter'

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
