language: ruby

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

sudo: false

before_install:
  - gem install bundler --no-document
script:
  - 'bundle exec rspec'
after_success:
  - 'bundle exec codeclimate-test-reporter'

cache: bundler
